version: '3'
services:
  php:
    image: php:7.3-alpine
    ports:
      - 8000:8000
    working_dir: /var/www/html
    command:
      - php
      - artisan
      - serve
      - --host
      - 0.0.0.0
    volumes:
      - ./:/var/www/html
